#--------------------------------------------
# ft_ascii
#--------------------------------------------
ASCII_DIR	:=	ft_ascii
ASCII_SRC	:=	$(ASCII_DIR)/ft_isalnum.c \
				$(ASCII_DIR)/ft_isalpha.c \
				$(ASCII_DIR)/ft_isascii.c \
				$(ASCII_DIR)/ft_isdigit.c \
				$(ASCII_DIR)/ft_isprint.c \
				$(ASCII_DIR)/ft_tolower.c \
				$(ASCII_DIR)/ft_toupper.c

#--------------------------------------------
# ft_deque
#--------------------------------------------
DEQUE_DIR	:=	ft_deque
DEQUE_SRC	:=	$(DEQUE_DIR)/dq_add_back.c \
				$(DEQUE_DIR)/dq_add_front.c \
				$(DEQUE_DIR)/dq_clear_all.c \
				$(DEQUE_DIR)/dq_clear_node.c \
				$(DEQUE_DIR)/dq_is_empty.c \
				$(DEQUE_DIR)/dq_new.c \
				$(DEQUE_DIR)/dq_node_new.c \
				$(DEQUE_DIR)/dq_pop_back.c \
				$(DEQUE_DIR)/dq_pop_front.c \
				$(DEQUE_DIR)/dq_pop_selected_node.c \
				$(DEQUE_DIR)/dq_print.c \
				$(DEQUE_DIR)/dq_set_node.c

#--------------------------------------------
# ft_lib
#--------------------------------------------
LIB_DIR		:=	ft_lib
LIB_SRC		:=	$(LIB_DIR)/ft_atoi_old.c \
				$(LIB_DIR)/ft_atoi_strictly.c \
				$(LIB_DIR)/ft_atoi.c \
				$(LIB_DIR)/ft_itoa_int.c \
				$(LIB_DIR)/ft_itoa.c \
				$(LIB_DIR)/ft_strtol.c

#--------------------------------------------
# ft_list
#--------------------------------------------
LIST_DIR	:=	ft_list
LIST_SRC	:=	$(LIST_DIR)/ft_lstadd_back.c \
				$(LIST_DIR)/ft_lstadd_front.c \
				$(LIST_DIR)/ft_lstclear.c \
				$(LIST_DIR)/ft_lstdelone.c \
				$(LIST_DIR)/ft_lstiter.c \
				$(LIST_DIR)/ft_lstlast.c \
				$(LIST_DIR)/ft_lstmap.c \
				$(LIST_DIR)/ft_lstnew.c \
				$(LIST_DIR)/ft_lstsize.c

#--------------------------------------------
# ft_math
#--------------------------------------------
MATH_DIR	:=	ft_math
MATH_SRC	:=	$(MATH_DIR)/ft_max.c \
				$(MATH_DIR)/ft_min.c

#--------------------------------------------
# ft_mem
#--------------------------------------------
MEM_DIR		:=	ft_mem
MEM_SRC		:=	$(MEM_DIR)/ft_bzero.c \
				$(MEM_DIR)/ft_calloc.c \
				$(MEM_DIR)/ft_memchr.c \
				$(MEM_DIR)/ft_memcmp.c \
				$(MEM_DIR)/ft_memcpy.c \
				$(MEM_DIR)/ft_memmove.c \
				$(MEM_DIR)/ft_memset.c

#--------------------------------------------
# ft_put
#--------------------------------------------
PUT_DIR		:=	ft_put
PUT_SRC		:=	$(PUT_DIR)/ft_putchar_fd.c \
				$(PUT_DIR)/ft_putendl_fd.c \
				$(PUT_DIR)/ft_putnbr_fd.c \
				$(PUT_DIR)/ft_putstr_fd.c

#--------------------------------------------
# ft_string
#--------------------------------------------
STRING_DIR	:=	ft_string
STRING_SRC	:=	$(STRING_DIR)/ft_free.c \
				$(STRING_DIR)/ft_split.c \
				$(STRING_DIR)/ft_strchr.c \
				$(STRING_DIR)/ft_strdup.c \
				$(STRING_DIR)/ft_streq.c \
				$(STRING_DIR)/ft_striteri.c \
				$(STRING_DIR)/ft_strjoin.c \
				$(STRING_DIR)/ft_strlcat.c \
				$(STRING_DIR)/ft_strlcpy_void.c \
				$(STRING_DIR)/ft_strlcpy.c \
				$(STRING_DIR)/ft_strlen.c \
				$(STRING_DIR)/ft_strmapi.c \
				$(STRING_DIR)/ft_strncmp.c \
				$(STRING_DIR)/ft_strndup.c \
				$(STRING_DIR)/ft_strnlen.c \
				$(STRING_DIR)/ft_strnstr.c \
				$(STRING_DIR)/ft_strrchr.c \
				$(STRING_DIR)/ft_strtrim.c \
				$(STRING_DIR)/ft_substr.c

#--------------------------------------------
# ft_dprintf
#--------------------------------------------
FT_DPRINTF_DIR	:=	ft_dprintf
FT_DPRINTF_SRC	:=	$(FT_DPRINTF_DIR)/convert_to_str.c \
					$(FT_DPRINTF_DIR)/convert_to_str2.c \
					$(FT_DPRINTF_DIR)/ft_dprintf.c \
					$(FT_DPRINTF_DIR)/handle_info.c \
					$(FT_DPRINTF_DIR)/itoa_utoa_for_printf.c\
					$(FT_DPRINTF_DIR)/parse_format.c \
					$(FT_DPRINTF_DIR)/ptoa_xtoa_for_printf.c \
					$(FT_DPRINTF_DIR)/set_field.c \
					$(FT_DPRINTF_DIR)/set_output.c \
					$(FT_DPRINTF_DIR)/strdup_for_printf.c

#--------------------------------------------
# ft_sys
#--------------------------------------------
SYS_DIR	:=	ft_sys
SYS_SRC	:=	$(SYS_DIR)/x_access.c \
			$(SYS_DIR)/x_chdir.c \
			$(SYS_DIR)/x_close.c \
			$(SYS_DIR)/x_closedir.c \
			$(SYS_DIR)/x_dup.c \
			$(SYS_DIR)/x_dup2.c \
			$(SYS_DIR)/x_execve.c \
			$(SYS_DIR)/x_fork.c \
			$(SYS_DIR)/x_getcwd.c \
			$(SYS_DIR)/x_isatty.c \
			$(SYS_DIR)/x_kill.c \
			$(SYS_DIR)/x_malloc.c \
			$(SYS_DIR)/x_open.c \
			$(SYS_DIR)/x_opendir.c \
			$(SYS_DIR)/x_pipe.c \
			$(SYS_DIR)/x_read.c \
			$(SYS_DIR)/x_readdir.c \
			$(SYS_DIR)/x_sigaction.c \
			$(SYS_DIR)/x_signal.c \
			$(SYS_DIR)/x_tcgetattr.c \
			$(SYS_DIR)/x_tcsetattr.c \
			$(SYS_DIR)/x_ttyname.c \
			$(SYS_DIR)/x_unlink.c \
			$(SYS_DIR)/x_wait.c \
			$(SYS_DIR)/x_waitpid.c \
			$(SYS_DIR)/x_write.c

#--------------------------------------------
NAME		:=	libft.a

SRCS_DIR	:=	srcs
OBJS_DIR	:=	objs
OBJS		:=	$(DEQUE_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(ASCII_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(LIB_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(LIST_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(MATH_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(MEM_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(PUT_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(STRING_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(FT_DPRINTF_SRC:%.c=$(OBJS_DIR)/%.o) \
				$(SYS_SRC:%.c=$(OBJS_DIR)/%.o)

#--------------------------------------------
INCLUDES_DIR	:=	includes
INCLUDES		:=	-I$(INCLUDES_DIR)/

DEPS		:=	$(OBJS:.o=.d)

#--------------------------------------------
CC			:=	cc
CFLAGS		:=	-Wall -Wextra -Werror -MMD -MP
ARFLAGS		:=	rcs
MKDIR		:=	mkdir -p

#--------------------------------------------
all: $(NAME)

-include $(DEPS)

$(OBJS_DIR)/%.o: $(SRCS_DIR)/%.c
	@$(MKDIR) $(dir $@)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(NAME): $(OBJS)
	$(AR) $(ARFLAGS) $(NAME) $(OBJS)

clean:
	$(RM) -r $(OBJS_DIR)

fclean: clean
	$(RM) $(NAME)

re: fclean all

#--------------------------------------------
info:
	$(info >>> default goal : $(.DEFAULT_GOAL))
	$(info >>> obj : $(OBJS))

.PHONY: all clean fclean re info
