name: bats
on:
  push:
    branches: [ "dev", "playground/act-test-1" ]
  pull_request:
    branches: [ "dev", "playground/act-test-1" ]

  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1.2.0

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: ./.github/sh/test.bats
