name: bats
on:
  push:
    branches: [ "dev", ]
  pull_request:
    branches: [ "dev", ]

  workflow_dispatch:

#jobs:
#  check-bats-version:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup BATS testing framework
#        uses: mig4/setup-bats@v1.2.0
#
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '14'
#      - run: npm install -g bats
#      - run: bats -v
#      - run: ./.github/sh/test.bats

jobs:
  check-bats-version:
    name: "bats test"
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v3
      - name: check bats version
        run: bats -v
      - name: run test
        working-directory: .github/sh
        run: bats -r .
        shell: bash