# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Norminette.
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      # Runs a single command using the runners shell
      # アクションの終了コードの設定 - GitHub Docs => 終了ステータス0以外ならfailureが出ます。
      # https://docs.github.com/ja/actions/creating-actions/setting-exit-codes-for-actions
      - name: Norm check.
        run: python3 sh/norm.py
