name: Unit test
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run all unit test.
        run: |
          chmod +x test/unit_test/unit_test.sh
          ./test/unit_test/unit_test.sh